services:
  polling-inspector:
    build: .
    container_name: polling-inspector
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
